source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'NNPopoverButton_Example' do
  pod 'NNPopoverButton', :path => '../'

  target 'NNPopoverButton_Tests' do
    inherit! :search_paths

    
  end
end
